/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;


import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Jovi MONG
 */
public class CariKamar extends javax.swing.JInternalFrame {
    Connection con;
    Statement st;
    ResultSet rs;
    
    
    
    
    /**
     * Creates new form CariKamar
     */
    public CariKamar() {
        initComponents();
        tabel();
      
      
    }
    
    
 public void tabel(){
     DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Nama");
            tbl.addColumn("Kelas");
            tbl.addColumn("Nomor");
            tbl.addColumn("Harga");
            tbl.addColumn("Keterangan");
        jTable1.setModel(tbl);
        try{
            st = (Statement) koneksi.getkoneksi().createStatement();
            String sql = "select nama,kelas,nomor,harga, keterangan from kamar where kelas='ekonomi'";
            rs = st.executeQuery(sql);
            while (rs.next()){
                tbl.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)});
                jTable1.setModel(tbl);
            }
            
        }catch(Exception e){
            System.out.println(e.getMessage());
            
        }
    
    DefaultTableModel tbl2 = new DefaultTableModel();
            tbl2.addColumn("Nama");
            tbl2.addColumn("Kelas");
            tbl2.addColumn("Nomor");
            tbl2.addColumn("Harga");
            tbl2.addColumn("Keterangan");
        jTable2.setModel(tbl2);
        try{
            st = (Statement) koneksi.getkoneksi().createStatement();
            String sql = "select nama,kelas,nomor,harga,keterangan from kamar where kelas='VIP'";
            rs = st.executeQuery(sql);
            while (rs.next()){
                tbl2.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)});
                jTable2.setModel(tbl2);
            }
            
        }catch(Exception e){
            System.out.println(e.getMessage());
            
        }
        
        DefaultTableModel tbl3 = new DefaultTableModel();
            tbl3.addColumn("Nama");
            tbl3.addColumn("Kelas");
            tbl3.addColumn("Nomor");
            tbl3.addColumn("Harga");
            tbl3.addColumn("Keterangan");
        jTable3.setModel(tbl3);
        try{
            st = (Statement) koneksi.getkoneksi().createStatement();
            String sql = "select nama,kelas,nomor,harga,keterangan from kamar where kelas='VVIP'";
            rs = st.executeQuery(sql);
            while (rs.next()){
                tbl3.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)});
                jTable3.setModel(tbl3);
            }
            
        }catch(Exception e){
            System.out.println(e.getMessage());
            
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jButtonTersedia = new javax.swing.JButton();
        jButtonSemua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButtonTersedia.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonTersedia.setText("Tersedia");
        jButtonTersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTersediaActionPerformed(evt);
            }
        });

        jButtonSemua.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonSemua.setText("Semua");
        jButtonSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSemuaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("FILTER");

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("Ekonomi", jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("VIP", jScrollPane2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTabbedPane1.addTab("VVIP", jScrollPane3);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("INFORMASI KAMAR TIAP KELAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButtonSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSemua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 18, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButtonTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTersediaActionPerformed
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex()==0){
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("Nama");
            tbl.addColumn("Kelas");
            tbl.addColumn("Nomor");
            tbl.addColumn("Harga");
            tbl.addColumn("Keterangan");
        jTable1.setModel(tbl);
        try{
            String sql = "select nama, kelas, nomor, harga, keterangan from kamar where keterangan='tersedia' and kelas='ekonomi'";
            rs = st.executeQuery(sql);
            while (rs.next()){
                tbl.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)});
                jTable1.setModel(tbl);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        }else if(jTabbedPane1.getSelectedIndex()==1){
            
            DefaultTableModel tbl2 = new DefaultTableModel();
            tbl2.addColumn("Nama");
            tbl2.addColumn("Kelas");
            tbl2.addColumn("Nomor");
            tbl2.addColumn("Harga");
            tbl2.addColumn("Keterangan");
        jTable2.setModel(tbl2);
        try{
            String sql = "select nama, kelas, nomor,harga, keterangan from kamar where keterangan='tersedia' and kelas='VIP'";
            rs = st.executeQuery(sql);
            while (rs.next()){
                tbl2.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)});
                jTable2.setModel(tbl2);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        }else{
            DefaultTableModel tbl3 = new DefaultTableModel();
            tbl3.addColumn("Nama");
            tbl3.addColumn("Kelas");
            tbl3.addColumn("Nomor");
            tbl3.addColumn("Harga");
            tbl3.addColumn("Keterangan");
        jTable3.setModel(tbl3);
        try{
            String sql = "select nama, kelas, nomor,harga, keterangan from kamar where keterangan='tersedia' and kelas='VVIP'";
            rs = st.executeQuery(sql);
            while (rs.next()){
                tbl3.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)});
                jTable3.setModel(tbl3);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        }
    }//GEN-LAST:event_jButtonTersediaActionPerformed

    private void jButtonSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSemuaActionPerformed
        // TODO add your handling code here:
        tabel();
    }//GEN-LAST:event_jButtonSemuaActionPerformed
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSemua;
    private javax.swing.JButton jButtonTersedia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
