/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemrograman;

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuFormulir = new javax.swing.JMenuItem();
        MenuTransaksi = new javax.swing.JMenuItem();
        MenuKeluar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuFilm = new javax.swing.JMenuItem();
        MenuPetugas = new javax.swing.JMenuItem();
        MenuPenonton = new javax.swing.JMenuItem();
        MenuRuangan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        MenuFormulir.setText("Isi Formulir");
        MenuFormulir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFormulirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuFormulir);

        MenuTransaksi.setText("Transaksi");
        MenuTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTransaksiActionPerformed(evt);
            }
        });
        jMenu1.add(MenuTransaksi);

        MenuKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemrograman/gambar/keluar.png"))); // NOI18N
        MenuKeluar.setText("Keluar");
        MenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKeluarActionPerformed(evt);
            }
        });
        jMenu1.add(MenuKeluar);

        jMenuItem1.setText("Kunci");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        MenuFilm.setText("Data Film");
        MenuFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFilmActionPerformed(evt);
            }
        });
        jMenu2.add(MenuFilm);

        MenuPetugas.setText("Data Petugas");
        MenuPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPetugasActionPerformed(evt);
            }
        });
        jMenu2.add(MenuPetugas);

        MenuPenonton.setText("Data Penonton");
        MenuPenonton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPenontonActionPerformed(evt);
            }
        });
        jMenu2.add(MenuPenonton);

        MenuRuangan.setText("Data Ruangan");
        jMenu2.add(MenuRuangan);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuFormulirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFormulirActionPerformed
        // TODO add your handling code here:
        new formulir_penonton().setVisible(true);
        //dispose();
        
    }//GEN-LAST:event_MenuFormulirActionPerformed

    private void MenuTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTransaksiActionPerformed
        // TODO add your handling code here:
        new transaksi().setVisible(true);
    }//GEN-LAST:event_MenuTransaksiActionPerformed

    private void MenuFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFilmActionPerformed
        // TODO add your handling code here:
        new Data_Film().setVisible(true);        
    }//GEN-LAST:event_MenuFilmActionPerformed

    private void MenuPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPetugasActionPerformed
        // TODO add your handling code here:
        new Data_Petugas().setVisible(true);
    }//GEN-LAST:event_MenuPetugasActionPerformed

    private void MenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuKeluarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuPenontonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPenontonActionPerformed
        // TODO add your handling code here:
        new Data_penonton().setVisible(true);
    }//GEN-LAST:event_MenuPenontonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuFilm;
    private javax.swing.JMenuItem MenuFormulir;
    private javax.swing.JMenuItem MenuKeluar;
    private javax.swing.JMenuItem MenuPenonton;
    private javax.swing.JMenuItem MenuPetugas;
    private javax.swing.JMenuItem MenuRuangan;
    private javax.swing.JMenuItem MenuTransaksi;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
