/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemrograman;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import pemrograman.Data_penonton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class Pilih_Film extends javax.swing.JFrame {
    Connection cnn;
    ResultSet rss;
    Statement stt;

    /**
     * Creates new form film
     */
    public Pilih_Film() {
        initComponents();
        this.setLocationRelativeTo(null);
        clear();
        tabel();
    }
    
    public void clear(){
        txtcari.setText(null);
        
    }
    
    public void tabel(){
        DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("ID FILM");
            tbl.addColumn("JUDUL FILM");            
            tbl.addColumn("JENIS FILM");            
            tbl.addColumn("DURASI FILM");
            tbl.addColumn("TAHUN");
        Tablefilm.setModel(tbl);
        try{
            stt = (Statement) koneksi.getkoneksi().createStatement();
            String sql = "select * from film order by id_film asc";
            rss = stt.executeQuery(sql);
            while (rss.next()){
                tbl.addRow(new Object[]{
                    rss.getString(1),
                    rss.getString(2),
                    rss.getString(3),
                    rss.getString(4),
                    rss.getString(5)});
                Tablefilm.setModel(tbl);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame2 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablefilm = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        txtcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        sgarkan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame2.setBackground(java.awt.Color.darkGray);
        jInternalFrame2.setVisible(true);
        jInternalFrame2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jInternalFrame2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Tablefilm.setBackground(java.awt.Color.darkGray);
        Tablefilm.setForeground(new java.awt.Color(255, 255, 255));
        Tablefilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tablefilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablefilmMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tablefilm);

        jPanel4.setBackground(java.awt.Color.darkGray);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CARI BERDASARKAN");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemrograman/gambar/cari.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        sgarkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemrograman/gambar/segar.png"))); // NOI18N
        sgarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgarkanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA FILM");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pemrograman/gambar/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sgarkan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(jLabel1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sgarkan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInternalFrame2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jInternalFrame2AncestorAdded
        // TODO add your handling code here:
        jComboBox1.removeAllItems();
        jComboBox1.addItem("JUDUL FILM");
        jComboBox1.addItem("JENIS FILM");
        jComboBox1.addItem("TAHUN FILM");
    }//GEN-LAST:event_jInternalFrame2AncestorAdded

    private void sgarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgarkanActionPerformed
        // TODO add your handling code here:
        tabel();
        clear();
    }//GEN-LAST:event_sgarkanActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex()==0){
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("ID FILM");
            tbl.addColumn("JUDUL FILM");
            tbl.addColumn("JENIS FILM");
            tbl.addColumn("DURASI FILM");
            tbl.addColumn("TAHUN");
            Tablefilm.setModel(tbl);
            try{
                String sql = "select * from film where judul_film like '"+txtcari.getText()+"'";
                rss = stt.executeQuery(sql);
                if (rss.next()){
                    tbl.addRow(new Object[]{
                        rss.getString(1),
                        rss.getString(2),
                        rss.getString(3),
                        rss.getString(4),
                        rss.getString(5)});
                Tablefilm.setModel(tbl);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
            tabel();
        }
        } else if (jComboBox1.getSelectedIndex()==1) {
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("ID FILM");
            tbl.addColumn("JUDUL FILM");
            tbl.addColumn("JENIS FILM");
            tbl.addColumn("DURASI FILM");
            tbl.addColumn("TAHUN");
            Tablefilm.setModel(tbl);
            try{
                String sql = "select * from film where jenis_film like '"+txtcari.getText()+"' ";
                rss = stt.executeQuery(sql);
                if (rss.next()){

                    tbl.addRow(new Object[]{
                        rss.getString(1),
                        rss.getString(2),
                        rss.getString(3),
                        rss.getString(4),
                        rss.getString(5)});
                Tablefilm.setModel(tbl);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
            tabel();
        }
        } else {
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("ID FILM");
            tbl.addColumn("JUDUL FILM");
            tbl.addColumn("JENIS FILM");
            tbl.addColumn("DURASI FILM");
            tbl.addColumn("TAHUN");
            Tablefilm.setModel(tbl);
            try{
                String sql = "select * from film where tahun like '"+txtcari.getText()+"'";
                rss = stt.executeQuery(sql);
                if (rss.next()){

                    tbl.addRow(new Object[]{
                        rss.getString(1),
                        rss.getString(2),
                        rss.getString(3),
                        rss.getString(4),
                        rss.getString(5)});
                Tablefilm.setModel(tbl);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
            tabel();
        }
        }
    }//GEN-LAST:event_cariActionPerformed

    private void TablefilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablefilmMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TablefilmMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pilih_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pilih_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pilih_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pilih_Film.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pilih_Film().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablefilm;
    private javax.swing.JButton cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sgarkan;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
